### ISSUE TITLE
cMake Error: The source directory "/contracts" does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by fiser321** [liquidapps-io/zeus-cmd#1]
run comand zeus unbox helloworld --test,then has some error ：

{ Error: exec failed
    at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.11.0/lib/node_modules/@liquidapps/zeus-cmd/dist/helpers/_exec.js:67:27)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
  stdout: '⚒Compile \u001b[32meos\u001b[39m\n',
  stderr:
   '{ Error: exec failed\n    at ChildProcess.<anonymous> (/root/helloworld/extensions/helpers/_exec.js:56:26)\n    at ChildProcess.emit (events.js:182:13)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)\n  stdout: \'\',\n  stderr:\n   \'CMake Error: The source directory "/contracts" does not appear to contain CMakeLists.txt.\\nSpecify --help for usage, or press the help button on the CMake GUI.\\n\',\n  code: 1 }\n',
  code: 1 }

**Comment by tmuskal** [comment]
which OS/version are you using?

can you try? 
```
npm update -g @liquidapps/zeus-cmd
zeus unbox helloworld
cd helloworld
zeus test
```
(after removing /root/helloworld)

thanks

**Comment by NatPDeveloper** [comment]
Closing due to inactivity. @fiser321 please feel free to continue the conversation if you like.
