### ISSUE TITLE
Error: zeus unbox `helloworld` invalid signature

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-cmd#2]
Not sure if the IPFS links are still working, but when I try to `unbox` it hangs for a couple minutes at the `unboxing` steps and then causes an error `invalid signature`

```
$ zeus unbox helloworld
⚙️Unboxing: helloworld
⚙️Unboxing: sample-eos-cpp
⚙️Unboxing: mocha,seed-eos,seed-migrations,hooks-cpp-contracts,eos-common
Error: invalid signature: 0x4f44213c
    at /usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Tried on MacOS & Ubuntu, both same results

**Comment by DenisCarriere** [comment]
Seem to work now
