### ISSUE TITLE
Issue unboxing `dapp-services` caused by [zeromq] dependency

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-cmd#4]
Seems like anytime I attempt to unbox `dapp-services` it crashes due to the `zeromq` dependency.

```
$ node -v
v10.15.3
$ npm -v
6.4.1
```

Seems like the latest release of `zeromq@5.1.0` does contain the `prebuild-install.js` script:

https://unpkg.com/zeromq@5.1.0/scripts/

Been able to install `zero` using the `--unsafe-perm` flag:

```
 npm install --unsafe-perm zeromq
```

```bash
$ zeus unbox dapp-services
⚙️Unboxing: dapp-services
⚙️Unboxing: seed,seed-microservices,core-extensions,demux,seed-eos,events,seed-models,hooks-cpp-contracts
⚙️Unboxing: hooks-npm,seed-zeus-support
⚙️Unboxing: hooks-extensions
⚙️Unboxing: seed-extensions,seed-zeus-support
⚙️Unboxing: seed-zeus-base
⚙️Unboxing: seed-empty
☄️post-install hook for box: seed-zeus-base
⚙️Unboxing: core-extensions
⚙️Unboxing: run-extensions,migrations-extensions,contract-migrations-extensions,test-extensions,build-extensions,localenv-extensions,upgrade-extensions,unbox-extensions,build-extensions,create-extensions,update-extensions
⚙️Unboxing: seed-models
✴️NPM Install js-yaml
⚙️Unboxing: localenv-extensions,seed-eos,zeus-eos
⚙️Unboxing: eos-extensions,zeus-eos,eos-common
✴️NPM Install eosjs eosjs-ecc eosjs2
⚙️Unboxing: events
☄️post-install hook for box: seed-eos
✴️NPM Install mkdirp
✴️NPM Install unzip
⚙️Unboxing: repo-zeusrepoeos
☄️post-install hook for box: update-extensions
✴️NPM Install daemonize-process kill-port
✴️NPM Install @types/jest babel-polyfill eosjs-ecc text-encoding ws pako node-fetch zeromq
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/dapp-services/node_modules/zeromq/scripts/prebuild-install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/dapp-services/node_modules/zeromq/scripts/preinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-20T12_46_56_497Z-debug.log

Error: npm install failed
    at _callee2$ (/root/dapp-services/extensions/hooks/post-install/01-npm.js:17:19)
    at tryCatch (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/lib/node_modules/@liquidapps/zeus-cmd/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/root/dapp-services/extensions/hooks/post-install/01-npm.js:5:191)
    at /root/dapp-services/extensions/hooks/post-install/01-npm.js:5:402
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by tmuskal** [comment]
Hi Denis,
If running as root: (and not inside docker)
you can run:
`npm config set unsafe-perm true`
to instruct npm to pass this flag for every install

**Comment by DenisCarriere** [comment]
👍 beauty, that works!
