### ISSUE TITLE
demux service missing `express` dependency

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-cmd#5]
```
$ zeus --version
1.8.453
```
```bash
zeus unbox demux
cd demux
node services/demux/index.js
```

**error logs**
```
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/denis/Github/demux/services/demux/index.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

**Comment by NatPDeveloper** [comment]
Hey Denis, thank you for posting this.

You should be able to get past this error with:

```sh
npm install --save express
```
